//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectWatcher.Resources.EnglishText", typeof(EnglishText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last User.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available properties.
        /// </summary>
        internal static string AvailableProperties {
            get {
                return ResourceManager.GetString("AvailableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to project.
        /// </summary>
        internal static string BackToProjectView {
            get {
                return ResourceManager.GetString("BackToProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad column definition.
        /// </summary>
        internal static string BadColumnDefinition {
            get {
                return ResourceManager.GetString("BadColumnDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property caption.
        /// </summary>
        internal static string BadDisplayType {
            get {
                return ResourceManager.GetString("BadDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad csv-file format.
        /// </summary>
        internal static string BadInputCsvFileFormat {
            get {
                return ResourceManager.GetString("BadInputCsvFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property programname.
        /// </summary>
        internal static string BadPropertySystemName {
            get {
                return ResourceManager.GetString("BadPropertySystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of the property.
        /// </summary>
        internal static string BadPropertyType {
            get {
                return ResourceManager.GetString("BadPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in definitions of project with this ids:.
        /// </summary>
        internal static string BeginOfErrorInUploadingFiles {
            get {
                return ResourceManager.GetString("BeginOfErrorInUploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while connecting to the database.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new property.
        /// </summary>
        internal static string CreateProperty {
            get {
                return ResourceManager.GetString("CreateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading.
        /// </summary>
        internal static string ErrorWhileUploading {
            get {
                return ResourceManager.GetString("ErrorWhileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import succeded.
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is important.
        /// </summary>
        internal static string IsImportant {
            get {
                return ResourceManager.GetString("IsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects with: .
        /// </summary>
        internal static string LabelBeforeFilter {
            get {
                return ResourceManager.GetString("LabelBeforeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough rights.
        /// </summary>
        internal static string NotEnoughRights {
            get {
                return ResourceManager.GetString("NotEnoughRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough rights for modifying projects with ids:.
        /// </summary>
        internal static string NotEnoughRightsForModifying {
            get {
                return ResourceManager.GetString("NotEnoughRightsForModifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project properties.
        /// </summary>
        internal static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Info.
        /// </summary>
        internal static string PropertyInfo {
            get {
                return ResourceManager.GetString("PropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name.
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string TheProject1 {
            get {
                return ResourceManager.GetString("TheProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values in enumeration.
        /// </summary>
        internal static string ValuesInEnumeration {
            get {
                return ResourceManager.GetString("ValuesInEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong table definition.
        /// </summary>
        internal static string WrongTableDefinition {
            get {
                return ResourceManager.GetString("WrongTableDefinition", resourceCulture);
            }
        }
    }
}
